<?php

use Illuminate\Database\Seeder;

class QuizTableSeeder extends Seeder
{
    /**
     * Run the database seeds.
     *
     * @return void
     */
    public function run()
    {
        DB::table('quizzes')->truncate();

        DB::table('quizzes')->insert(
          [
            //①元素鉱物
            [
              'title' => '成分が火山ガスに多量に含まれているため、火山の多い日本では各地の火山噴気孔などで結晶を見ることができる。',
              'answers_id' => 1,
              'categories_id' => 1,
              'created_at' => now(),
              'updated_at' => now(),
              'image_src' => '元素_硫黄.jpg',
            ],
            [
              'title' => '美しい光沢を持ち、世界中で通貨にされたり、装飾品として珍重されている。',
              'answers_id' => 2,
              'categories_id' => 1,
              'created_at' => now(),
              'updated_at' => now(),
              'image_src' => '元素_自然金.jpeg',
            ],
            [
              'title' => '細長い糸やひものようなかたちで算出される。通電生がよく、耐食性に優れており、メッキに使われるなど工業的な価値が高い。',
              'answers_id' => 3,
              'categories_id' => 1,
              'created_at' => now(),
              'updated_at' => now(),
              'image_src' => '元素_自然銀.jpg',
            ],
            [
              'title' => '金属の中でも特に優れた熱伝導性と導電性を持つ。 その特性から熱交換器や電子機器の材料として使われる。',
              'answers_id' => 4,
              'categories_id' => 1,
              'created_at' => now(),
              'updated_at' => now(),
              'image_src' => '元素_自然銅.jpeg',
            ],
            [
              'title' => '白い光沢を持つ金属として存在する。化学的に非常に安定であるため、装飾品に多く利用される一方、触媒としても使われる。',
              'answers_id' => 5,
              'categories_id' => 1,
              'created_at' => now(),
              'updated_at' => now(),
              'image_src' => '元素_白金.jpg',
            ],
            //②酸化鉱物

            [
              'title' => 'ガラスなどの原料に用いられるほか、時計の発振子、ライトなど多く利用される。最もポピュラーな鉱物。',
              'answers_id' => 6,
              'categories_id' => 2,
              'created_at' => now(),
              'updated_at' => now(),
              'image_src' => '酸化_石英.jpg',
            ],
            [
              'title' => '石英とは同質異像。二酸化ケイ素は低温（870℃以下）では石英になるが、高温（870℃以上、1470℃以下）ではこの鉱物になる。',
              'answers_id' => 7,
              'categories_id' => 2,
              'created_at' => now(),
              'updated_at' => now(),
              'image_src' => '酸化_鱗珪石.jpg',
            ],
            [
              'title' => '石英とは同質異像。結晶には、8面体の小さな乳白色の粒状のものや、放射状の結晶が集合してできた球体を成したものもある。',
              'answers_id' => 8,
              'categories_id' => 2,
              'created_at' => now(),
              'updated_at' => now(),
              'image_src' => '酸化_方珪石.jpeg',
            ],
            [
              'title' => '黄鉄鉱などが風化・分解して生成する。',
              'answers_id' => 9,
              'categories_id' => 2,
              'created_at' => now(),
              'updated_at' => now(),
              'image_src' => '酸化_赤銅鉱.jpg',
            ],
            [
              'title' => '鉄の原料となる中心的な鉱物。どれも条痕色は赤錆色である。',
              'answers_id' => 10,
              'categories_id' => 2,
              'created_at' => now(),
              'updated_at' => now(),
              'image_src' => '酸化_赤鉄鉱.jpg',
            ],
            [
              'title' => 'チタンの重要な鉱石鉱物。',
              'answers_id' => 11,
              'categories_id' => 2,
              'created_at' => now(),
              'updated_at' => now(),
              'image_src' => '酸化_チタン鉄鉱.jpg',
            ],
            [
              'title' => '結晶は、小さな針状になりやすい。この鉱物が入り込んだルビーはスター・ルビーと呼ばれる。',
              'answers_id' => 12,
              'categories_id' => 2,
              'created_at' => now(),
              'updated_at' => now(),
              'image_src' => '酸化_金紅石.jpg',
            ],
            [
              'title' => '鋭い錐形の結晶が特徴で、錐面に横に細かい条線が見られる',
              'answers_id' => 13,
              'categories_id' => 2,
              'created_at' => now(),
              'updated_at' => now(),
              'image_src' => '酸化_鋭錐石.jpg',
            ],
            [
              'title' => '二酸化マンガン鉱物のひとつ。',
              'answers_id' => 14,
              'categories_id' => 2,
              'created_at' => now(),
              'updated_at' => now(),
              'image_src' => '酸化_軟マンガン鉱.jpg',
            ],
            [
              'title' => 'この鉱物から作られるものは、青銅器の原料として古くから利用されており、錆びにくく、薬品におかされにくいという特徴がある。',
              'answers_id' => 15,
              'categories_id' => 2,
              'created_at' => now(),
              'updated_at' => now(),
              'image_src' => '酸化_スズ石.jpg',
            ],
            [
              'title' => 'ある原子力に使われる資源を含む。',
              'answers_id' => 16,
              'categories_id' => 2,
              'created_at' => now(),
              'updated_at' => now(),
              'image_src' => '酸化_閃ウラン鉱.jpg',
            ],
            [
              'title' => '磁石に引き寄せられる、珍しい鉱物で、岩石中に含まれていた○○(鉱物名)が風化で分離したものが砂鉄の正体。',
              'answers_id' => 17,
              'categories_id' => 2,
              'created_at' => now(),
              'updated_at' => now(),
              'image_src' => '酸化_磁鉄鉱.jpg',
            ],
            [
              'title' => '磁鉄鉱などと同様にスピネル型結晶構造を取るスピネルグループの鉱物。',
              'answers_id' => 18,
              'categories_id' => 2,
              'created_at' => now(),
              'updated_at' => now(),
              'image_src' => '酸化_クロム鉄鉱.jpg',
            ],
            [
              'title' => '英名は『ゲーサイト』で、ドイツの文豪ゲーテに因んだもの。',
              'answers_id' => 19,
              'categories_id' => 2,
              'created_at' => now(),
              'updated_at' => now(),
              'image_src' => '酸化_針鉄鉱.jpg',
            ],
            [
              'title' => 'アルミニウムの原料であるボーキサイトの主成分である。',
              'answers_id' => 20,
              'categories_id' => 2,
              'created_at' => now(),
              'updated_at' => now(),
              'image_src' => '酸化_ギプス石.jpg',
            ],

            //③炭酸塩鉱物

            [
              'title' => '方解石と同質異像の鉱物である。和名は、外観が○○のような石だからという理由で江戸時代に命名されたもの。',
              'answers_id' => 21,
              'categories_id' => 3,
              'created_at' => now(),
              'updated_at' => now(),
              'image_src' => '炭酸_霰石.jpg',
            ],
            [
              'title' => '石灰岩や大理石や鍾乳石を構成している鉱物。一本の直線上に方解石を置くと、屈折率の影響で直線は二重にみえる。',
              'answers_id' => 22,
              'categories_id' => 3,
              'created_at' => now(),
              'updated_at' => now(),
              'image_src' => '炭酸_方解石.jpg',
            ],
            [
              'title' => 'この鉱物からとれる原料は消毒液や下剤などの薬品、インク、ガラス、光学装置、耐火材料などに用いられる。',
              'answers_id' => 23,
              'categories_id' => 3,
              'created_at' => now(),
              'updated_at' => now(),
              'image_src' => '炭酸_菱苦土石.jpg',
            ],
            [
              'title' => '別名インカ・ローズと呼ばれる。ある原料を得るための主要鉱物。',
              'answers_id' => 24,
              'categories_id' => 3,
              'created_at' => now(),
              'updated_at' => now(),
              'image_src' => '炭酸_菱マンガン鉱.jpg',
            ],
            [
              'title' => '製鉄の重要な鉱石として採掘されている。',
              'answers_id' => 25,
              'categories_id' => 3,
              'created_at' => now(),
              'updated_at' => now(),
              'image_src' => '炭酸_菱鉄鉱.jpg',
            ],
            [
              'title' => '多くは亜鉛鉱床などの酸化帯から産出される2次鉱物。',
              'answers_id' => 26,
              'categories_id' => 3,
              'created_at' => now(),
              'updated_at' => now(),
              'image_src' => '炭酸_菱亜鉛鉱.jpg',
            ],
            [
              'title' => '青色の顔料として利用されてきた。結晶のかたちは柱状または板状のものが多く、一見黒く見えるほど濃藍青色をしている。',
              'answers_id' => 27,
              'categories_id' => 3,
              'created_at' => now(),
              'updated_at' => now(),
              'image_src' => '炭酸_藍銅鉱.jpg',
            ],
            [
              'title' => 'マカライト・グリーンと呼ばれる。純粋なものは顔料に、塊状で美しいものは装飾品に利用される。',
              'answers_id' => 28,
              'categories_id' => 3,
              'created_at' => now(),
              'updated_at' => now(),
              'image_src' => '炭酸_孔雀石.jpg',
            ],
            [
              'title' => '比重が高いことから重量感がある。希塩酸をかけると白鉛鉱は泡を出して溶ける。',
              'answers_id' => 29,
              'categories_id' => 3,
              'created_at' => now(),
              'updated_at' => now(),
              'image_src' => '炭酸_白鉛鉱.jpg',
            ],
           
            //④珪酸塩鉱物
            [
              'title' => '黄緑色が特徴的だが、濃緑色、黒緑色などの色調が見られる。色は含まれる鉄の量で決まる。',
              'answers_id' => 30,
              'categories_id' => 4,
              'created_at' => now(),
              'updated_at' => now(),
              'image_src' => '珪酸_緑簾石.jpg',
            ],
            [
              'title' => '紅色が特徴的で、鮮やかな褐色や、ピンク色になったりもする。色は含まれるマンガンの量で決まる。',
              'answers_id' => 31,
              'categories_id' => 4,
              'created_at' => now(),
              'updated_at' => now(),
              'image_src' => '珪酸_紅簾石.jpg',
            ],
            [
              'title' => '高圧下で安定な結晶形である。濃い青色を示し、ガラスのような光沢を放つ。',
              'answers_id' => 32,
              'categories_id' => 4,
              'created_at' => now(),
              'updated_at' => now(),
              'image_src' => '珪酸_藍晶石.jpg',
            ],
            [
              'title' => '通常は柱状をしているが、その先端が上下で異なり、片方は錐面状に尖り、もう片方は平になっている。',
              'answers_id' => 33,
              'categories_id' => 4,
              'created_at' => now(),
              'updated_at' => now(),
              'image_src' => '珪酸_異極鉱.jpg',
            ],
            [
              'title' => '十字状の形をして産出される。',
              'answers_id' => 34,
              'categories_id' => 4,
              'created_at' => now(),
              'updated_at' => now(),
              'image_src' => '珪酸_十字石.jpg',
            ],
            [
              'title' => 'カルシウム、マグネシウム、鉄、アルミニウムなどの珪酸塩を主成分とする重要な造岩鉱物のグループ名。多くは8角柱をなす。',
              'answers_id' => 35,
              'categories_id' => 4,
              'created_at' => now(),
              'updated_at' => now(),
              'image_src' => '珪酸_輝石.jpg',
            ],
            [
              'title' => 'ピンク色やバラ色をした美しい石である。',
              'answers_id' => 36,
              'categories_id' => 4,
              'created_at' => now(),
              'updated_at' => now(),
              'image_src' => '珪酸_バラ輝石.jpg',
            ],
            [
              'title' => '宝石では呼び名が異なり、アイドクレーズと呼ばれる。',
              'answers_id' => 37,
              'categories_id' => 4,
              'created_at' => now(),
              'updated_at' => now(),
              'image_src' => '珪酸_ベスブ石.jpg',
            ],
            [
              'title' => '鋭い刃のような板状結晶をするのが特徴。化学組成の違いから現在では4種類に細分されている。',
              'answers_id' => 38,
              'categories_id' => 4,
              'created_at' => now(),
              'updated_at' => now(),
              'image_src' => '珪酸_斧石.jpg',
            ],
            [
              'title' => '石灰岩に花崗岩が接触したことによる熱作用で変質したもの。セラミック・タイルやグラスファイバー、陶磁器などの原料として利用される。',
              'answers_id' => 39,
              'categories_id' => 4,
              'created_at' => now(),
              'updated_at' => now(),
              'image_src' => '珪酸_珪灰石.jpg',
            ],
            [
              'title' => 'カルシウム、マグネシウム、鉄などの珪酸塩と水酸基からなるグループ名。61種もの独立した鉱物を持つ。',
              'answers_id' => 40,
              'categories_id' => 4,
              'created_at' => now(),
              'updated_at' => now(),
              'image_src' => '珪酸_角閃石.jpg',
            ],
            [
              'title' => '見る角度によって白く濁った輝きがあり、それがある生き物のように見える。',
              'answers_id' => 41,
              'categories_id' => 4,
              'created_at' => now(),
              'updated_at' => now(),
              'image_src' => '珪酸_魚眼石.jpg',
            ],
            [
              'title' => '地殻中に普遍的に存在する鉱物で、もっとも存在量が多いグループ。',
              'answers_id' => 42,
              'categories_id' => 4,
              'created_at' => now(),
              'updated_at' => now(),
              'image_src' => '珪酸_長石.jpg',
            ],
            [
              'title' => '塩酸などの強酸に入れると白濁することから。ギリシャ語の” nephele”(雲の意味)にちなみ命名された。',
              'answers_id' => 43,
              'categories_id' => 4,
              'created_at' => now(),
              'updated_at' => now(),
              'image_src' => '珪酸_霞石.jpg',
            ],
            [
              'title' => '良質のものは宝石として扱われ、『アイオライト』、『ウォーターサファイア』とも呼ばれる。',
              'answers_id' => 44,
              'categories_id' => 4,
              'created_at' => now(),
              'updated_at' => now(),
              'image_src' => '珪酸_菫青石.jpg',
            ],
            [
              'title' => '薬品や化粧品、製紙、印材などに幅広く利用される。また、鉱物の中で最も柔らかい。',
              'answers_id' => 45,
              'categories_id' => 4,
              'created_at' => now(),
              'updated_at' => now(),
              'image_src' => '珪酸_滑石.jpg',
            ],
            [
              'title' => '長石の分解などによって生じた含水珪酸アルミナを含む細かい白色粘土の鉱物。',
              'answers_id' => 46,
              'categories_id' => 4,
              'created_at' => now(),
              'updated_at' => now(),
              'image_src' => '珪酸_カオリナイト.jpg',
            ],
            [
              'title' => '熱すると葉片状に剥がれる。石彫品、印材のほか、レンガの材料などにも利用される。',
              'answers_id' => 47,
              'categories_id' => 4,
              'created_at' => now(),
              'updated_at' => now(),
              'image_src' => '珪酸_葉蝋石.jpg',
            ],
            [
              'title' => '外観がある鉱物によく似ているためこの名前になったが、その鉱物のグループには属さない。',
              'answers_id' => 48,
              'categories_id' => 4,
              'created_at' => now(),
              'updated_at' => now(),
              'image_src' => '珪酸_葉長石.jpg',
            ],
            [
              'title' => '底辺に平行に薄い層のように薄く剥がれるのが特徴。種類も豊富。',
              'answers_id' => 49,
              'categories_id' => 4,
              'created_at' => now(),
              'updated_at' => now(),
              'image_src' => '珪酸_雲母.jpg',
            ],
            [
              'title' => '水分を含み加熱すると水蒸気を出す。8種類の独立した鉱物を含むグループ名。',
              'answers_id' => 50,
              'categories_id' => 4,
              'created_at' => now(),
              'updated_at' => now(),
              'image_src' => '珪酸_沸石.jpg',
            ],
            [
              'title' => 'くすんだ緑色～暗緑色で小さな片状をなし，軟らかく，薄くはがれる特徴がある。',
              'answers_id' => 51,
              'categories_id' => 4,
              'created_at' => now(),
              'updated_at' => now(),
              'image_src' => '珪酸_緑泥石.jpg',
            ],
            [
              'title' => '色は緑色、青緑色、青色で、不純物を含むと褐色や黒色を示す。純粋なものは硬度が低い。',
              'answers_id' => 52,
              'categories_id' => 4,
              'created_at' => now(),
              'updated_at' => now(),
              'image_src' => '珪酸_珪孔雀石.jpg',
            ],
            [
              'title' => '樹脂光沢や脂光沢を放ち、滑らかな脂感があって触るとすべすべしている。',
              'answers_id' => 53,
              'categories_id' => 4,
              'created_at' => now(),
              'updated_at' => now(),
              'image_src' => '珪酸_蛇紋石.jpg',
            ],

            //⑤硫化鉱物

            [
              'title' => '銀の硫化鉱物。もっとも重要な銀鉱石のひとつ。',
              'answers_id' => 54,
              'categories_id' => 5,
              'created_at' => now(),
              'updated_at' => now(),
              'image_src' => '硫化_輝銀鉱.jpg',
            ],
            [
              'title' => '銅の硫化鉱物。古くからの銅の重要な鉱石鉱物。',
              'answers_id' => 55,
              'categories_id' => 5,
              'created_at' => now(),
              'updated_at' => now(),
              'image_src' => '硫化_輝銅鉱.jpg',
            ],
            [
              'title' => '鉛の最も重要な鉱石鉱物。',
              'answers_id' => 56,
              'categories_id' => 5,
              'created_at' => now(),
              'updated_at' => now(),
              'image_src' => '硫化_方鉛鉱.jpg',
            ],
            [
              'title' => 'ほとんどの亜鉛をまかなうほど、亜鉛の重要な資源となっている。',
              'answers_id' => 57,
              'categories_id' => 5,
              'created_at' => now(),
              'updated_at' => now(),
              'image_src' => '硫化_閃亜鉛鉱.jpg',
            ],
            [
              'title' => '黄銅鉱は代表的な銅鉱石で、世界の銅の8割をカバーしているほど。',
              'answers_id' => 58,
              'categories_id' => 5,
              'created_at' => now(),
              'updated_at' => now(),
              'image_src' => '硫化_黄銅鉱.jpg',
            ],
            [
              'title' => '磁性を持っている硫化鉄鉱。結晶は6角形の板状が柱状のかたちをしているのが特徴。柱状では、柱の面に平行な縞模様の条痕が見られる。',
              'answers_id' => 59,
              'categories_id' => 5,
              'created_at' => now(),
              'updated_at' => now(),
              'image_src' => '硫化_磁硫鉄鉱.jpeg',
            ],
            [
              'title' => '銅の硫化鉱物としては珍しく鮮やかな藍色をしている。',
              'answers_id' => 60,
              'categories_id' => 5,
              'created_at' => now(),
              'updated_at' => now(),
              'image_src' => '硫化_銅藍.jpg',
            ],
            [
              'title' => '硫化水銀(II)からなる鉱物で。古くから水銀の材料や赤色の顔料として利用されてきた。',
              'answers_id' => 61,
              'categories_id' => 5,
              'created_at' => now(),
              'updated_at' => now(),
              'image_src' => '硫化_辰砂.jpg',
            ],
            [
              'title' => '硫化ヒ素を成分とする。赤やオレンジの鮮やかな色が特徴。',
              'answers_id' => 62,
              'categories_id' => 5,
              'created_at' => now(),
              'updated_at' => now(),
              'image_src' => '硫化_鶏冠石.jpg',
            ],
            [
              'title' => 'モース硬度は2であるため爪で引っ掻いても傷がつくほど柔らかい。',
              'answers_id' => 63,
              'categories_id' => 5,
              'created_at' => now(),
              'updated_at' => now(),
              'image_src' => '硫化_輝安鉱.jpg',
            ],
            [
              'title' => '希少金属の一つとされるビスマスの鉱石鉱物。',
              'answers_id' => 64,
              'categories_id' => 5,
              'created_at' => now(),
              'updated_at' => now(),
              'image_src' => '硫化_輝蒼鉛鉱.jpg',
            ],
            [
              'title' => '結晶のかたちは、主に6面体や5角12面体、立方体が一般的。英名の名前の由来はハンマーなどで叩くと火花が飛び散ることからギリシャ語の『花火』からきている。',
              'answers_id' => 65,
              'categories_id' => 5,
              'created_at' => now(),
              'updated_at' => now(),
              'image_src' => '硫化_黄鉄鉱.jpg',
            ],
            [
              'title' => 'コバルトの鉱石として重要。',
              'answers_id' => 66,
              'categories_id' => 5,
              'created_at' => now(),
              'updated_at' => now(),
              'image_src' => '硫化_輝コバルト鉱.jpg',
            ],
            [
              'title' => 'モリブデンの硫化鉱物。 見た目は雲母や石墨に類似している。',
              'answers_id' => 67,
              'categories_id' => 5,
              'created_at' => now(),
              'updated_at' => now(),
              'image_src' => '硫化_輝水鉛鉱.jpg',
            ],

            //⑥宝石
            [
              'title' => '鉱物の中で一番の硬度を誇る。',
              'answers_id' => 68,
              'categories_id' => 6,
              'created_at' => now(),
              'updated_at' => now(),
              'image_src' => '宝石_ダイアモンド.jpg',
            ],
            [
              'title' => 'クロムを含んでいるコランダムからなる。',
              'answers_id' => 69,
              'categories_id' => 6,
              'created_at' => now(),
              'updated_at' => now(),
              'image_src' => '宝石_ルビー.jpg',
            ],
            [
              'title' => 'コランダムという鉱物の中で赤色以外のもの。',
              'answers_id' => 70,
              'categories_id' => 6,
              'created_at' => now(),
              'updated_at' => now(),
              'image_src' => '宝石_サファイア.jpg',
            ],
            [
              'title' => 'クレオパトラに愛された宝石。地下深く大きな圧力を受けてできる石灰岩、黒雲母片岩と石英の接触鉱床の中で産することが多い。',
              'answers_id' => 71,
              'categories_id' => 6,
              'created_at' => now(),
              'updated_at' => now(),
              'image_src' => '宝石_エメラルド.jpg',
            ],
            [
              'title' => 'エメラルドと同じのベリルの仲間。',
              'answers_id' => 72,
              'categories_id' => 6,
              'created_at' => now(),
              'updated_at' => now(),
              'image_src' => '宝石_アクアマリン.jpg',
            ],
            [
              'title' => '水酸基(OH)タイプのものとフッ素(F)タイプのものがあり、実際には両成分が混合している。黄色いイメージがあるが色はさまざま。',
              'answers_id' => 73,
              'categories_id' => 6,
              'created_at' => now(),
              'updated_at' => now(),
              'image_src' => '宝石_トパーズ.jpg',
            ],
            [
              'title' => '原石はダイアモンドと同じように正八面体をしており、先端が尖っている。',
              'answers_id' => 74,
              'categories_id' => 6,
              'created_at' => now(),
              'updated_at' => now(),
              'image_src' => '宝石_スピネル.jpg',
            ],
            [
              'title' => 'その美しい輝きからダイアモンドの代替品として用いられてきた。',
              'answers_id' => 75,
              'categories_id' => 6,
              'created_at' => now(),
              'updated_at' => now(),
              'image_src' => '宝石_ジルコン.jpg',
            ],
            [
              'title' => '結晶を熱すると電気を帯びる性質がある。',
              'answers_id' => 76,
              'categories_id' => 6,
              'created_at' => now(),
              'updated_at' => now(),
              'image_src' => '宝石_トルマリン.jpg',
            ],
            [
              'title' => '日本ではざくろに似ていることからざくろ石と呼ばれる。',
              'answers_id' => 77,
              'categories_id' => 6,
              'created_at' => now(),
              'updated_at' => now(),
              'image_src' => '宝石_ガーネット.jpg',
            ],
            [
              'title' => 'ヒスイのことで、ヒスイと呼ばれる石は化学組成の違いから「◯◯」と「軟玉 (ネフライト)」に分かれる。',
              'answers_id' => 78,
              'categories_id' => 6,
              'created_at' => now(),
              'updated_at' => now(),
              'image_src' => '宝石_ジェード.jpg',
            ],
            [
              'title' => '潜晶質であるため厳密には準鉱物であり、特定の結晶を持たない。',
              'answers_id' => 79,
              'categories_id' => 6,
              'created_at' => now(),
              'updated_at' => now(),
              'image_src' => '宝石_オパール.jpg',
            ],
            [
              'title' => 'マントル上部の主要な成分で、玄武岩の中に見出すことができる。',
              'answers_id' => 80,
              'categories_id' => 6,
              'created_at' => now(),
              'updated_at' => now(),
              'image_src' => '宝石_ペリドット.jpg',
            ],
            [
              'title' => '紫色の水晶で、鉄イオンが放射線を受けることでスペクトルの変化が起こり変色したと言われている。',
              'answers_id' => 81,
              'categories_id' => 6,
              'created_at' => now(),
              'updated_at' => now(),
              'image_src' => '宝石_アメジスト.jpg',
            ],
            [
              'title' => '半透明で、非常に細かい結晶が集まった塊状の鉱物。',
              'answers_id' => 82,
              'categories_id' => 6,
              'created_at' => now(),
              'updated_at' => now(),
              'image_src' => '宝石_アゲート.jpg',
            ],
            [
              'title' => '硬度はダイアモンド、コランダムについで硬い。キャッツアイ、アレキサンドライトはこの鉱物の変種。',
              'answers_id' => 83,
              'categories_id' => 6,
              'created_at' => now(),
              'updated_at' => now(),
              'image_src' => '宝石_クリソベリル.jpg',
            ],
            [
              'title' => 'カーブした乳白色の石の表面に浮き上がっって見える青白い一条の光が特徴。',
              'answers_id' => 84,
              'categories_id' => 6,
              'created_at' => now(),
              'updated_at' => now(),
              'image_src' => '宝石_ムーンストーン.jpg',
            ],
            [
              'title' => 'トルコ石と呼ばれている。上質なものは美しい青色をしている。',
              'answers_id' => 85,
              'categories_id' => 6,
              'created_at' => now(),
              'updated_at' => now(),
              'image_src' => '宝石_ターコイズ.jpg',
            ],
            [
              'title' => '中世の画家たちは群青色の岩絵具として使用していた。',
              'answers_id' => 86,
              'categories_id' => 6,
              'created_at' => now(),
              'updated_at' => now(),
              'image_src' => '宝石_ラピスラズリ.jpg',
            ],
            [
              'title' => '天然樹脂の化石であり、宝石である。',
              'answers_id' => 87,
              'categories_id' => 6,
              'created_at' => now(),
              'updated_at' => now(),
              'image_src' => '宝石_アンバー.jpg',
            ],

            //⑦その他
            [
              'title' => '含有成分によって4つに大別される。リン酸カルシウムにフッ素が加わったものや、塩素、炭酸基、水酸基を主成分にするものがあり、それぞれ独立した鉱物となる。',
              'answers_id' => 88,
              'categories_id' => 7,
              'created_at' => now(),
              'updated_at' => now(),
              'image_src' => 'その他_燐灰石.jpg',
            ],
            [
              'title' => '濃縮ウランの原料となる放射性鉱物だが、燐灰ウラン鉱から出る放射能少ない。',
              'answers_id' => 89,
              'categories_id' => 7,
              'created_at' => now(),
              'updated_at' => now(),
              'image_src' => 'その他_燐灰ウラン鉱.jpg',
            ],
            [
              'title' => 'ギリシャ語の『ニンニクのような』から来ているほど、ニンニクのような臭いを発する。',
              'answers_id' => 90,
              'categories_id' => 7,
              'created_at' => now(),
              'updated_at' => now(),
              'image_src' => 'その他_スコロド石.jpg',
            ],
            [
              'title' => '地中にある時は無色透明だが、地表に出ると青色に変わっていく。',
              'answers_id' => 91,
              'categories_id' => 7,
              'created_at' => now(),
              'updated_at' => now(),
              'image_src' => 'その他_藍鉄鉱.jpg',
            ],
            [
              'title' => '名前は発見した鉱物学者にちなんで命名された。亜鉛とヒ素を含む金属鉱床の酸化帯に産する二次鉱物。',
              'answers_id' => 92,
              'categories_id' => 7,
              'created_at' => now(),
              'updated_at' => now(),
              'image_src' => 'その他_アダム鉱.jpg',
            ],
            [
              'title' => 'タングステン酸塩鉱物の一種。紫外線により青白く蛍光する。',
              'answers_id' => 93,
              'categories_id' => 7,
              'created_at' => now(),
              'updated_at' => now(),
              'image_src' => 'その他_灰重石.jpg',
            ],
            [
              'title' => '主成分はフッ化カルシウム、炭火などで強く熱すると発光する。',
              'answers_id' => 94,
              'categories_id' => 7,
              'created_at' => now(),
              'updated_at' => now(),
              'image_src' => 'その他_蛍石.jpg',
            ],
            [
              'title' => '鉱物として産する塩化ナトリウム。',
              'answers_id' => 95,
              'categories_id' => 7,
              'created_at' => now(),
              'updated_at' => now(),
              'image_src' => 'その他_岩塩.jpg',
            ],
            [
              'title' => '発見されたとき、人々は石だと気づかずに不思議な氷が出てきたと思ったとか。',
              'answers_id' => 96,
              'categories_id' => 7,
              'created_at' => now(),
              'updated_at' => now(),
              'image_src' => 'その他_氷晶石.jpg',
            ],
            [
              'title' => '150℃で石膏を焼いたものは像を造型するときなどの素材として使われる。',
              'answers_id' => 97,
              'categories_id' => 7,
              'created_at' => now(),
              'updated_at' => now(),
              'image_src' => 'その他_石膏.jpg',
            ],
            [
              'title' => 'バリウムの鉱石。他の非金属鉱物と比べて比重が重い。',
              'answers_id' => 98,
              'categories_id' => 7,
              'created_at' => now(),
              'updated_at' => now(),
              'image_src' => 'その他_重晶石.jpg',
            ],
            [
              'title' => '古くから、吐剤、除虫剤などに用いられる。銅の可溶性二次鉱物の一つ。',
              'answers_id' => 99,
              'categories_id' => 7,
              'created_at' => now(),
              'updated_at' => now(),
              'image_src' => 'その他_胆礬.jpg',
            ],
            [
              'title' => '母岩となる火山岩が火山性の噴気ガスや温泉の作用を受けた時にできる。この作用を「〇〇(鉱物名)化作用」という。',
              'answers_id' => 100,
              'categories_id' => 7,
              'created_at' => now(),
              'updated_at' => now(),
              'image_src' => 'その他_明礬石.jpeg',
            ]
          ]
        );
      }
    }