<?php

use Illuminate\Database\Seeder;

class QuizTableSeeder extends Seeder
{
    /**
     * Run the database seeds.
     *
     * @return void
     */
    public function run()
    {
        DB::table('quizzes')->truncate();

        DB::table('quizzes')->insert(
          [
            //①元素鉱物
            [
              'title' => '硫黄',
              'answers_id' => 1,
              'categories_id' => 1,
              'created_at' => now(),
              'updated_at' => now(),
              'image_src' => '元素_硫黄.png',
            ],
            [
              'title' => '自然金',
              'answers_id' => 2,
              'categories_id' => 1,
              'created_at' => now(),
              'updated_at' => now(),
              'image_src' => '元素_自然金.jpeg',
            ],
            [
              'title' => '自然銀',
              'answers_id' => 3,
              'categories_id' => 1,
              'created_at' => now(),
              'updated_at' => now(),
              'image_src' => '元素_自然銀.png',
            ],
            [
              'title' => '自然銅',
              'answers_id' => 4,
              'categories_id' => 1,
              'created_at' => now(),
              'updated_at' => now(),
              'image_src' => '元素_自然銅.jpeg',
            ],
            [
              'title' => '白金',
              'answers_id' => 5,
              'categories_id' => 1,
              'created_at' => now(),
              'updated_at' => now(),
              'image_src' => '元素_白金.png',
            ],
            //②酸化鉱物

            [
              'title' => 'クォーツ(石英)',
              'answers_id' => 6,
              'categories_id' => 2,
              'created_at' => now(),
              'updated_at' => now(),
              'image_src' => '酸化_石英.png',
            ],
            [
              'title' => '鱗珪石',
              'answers_id' => 7,
              'categories_id' => 2,
              'created_at' => now(),
              'updated_at' => now(),
              'image_src' => '酸化_鱗珪石.png',
            ],
            [
              'title' => '方珪石',
              'answers_id' => 8,
              'categories_id' => 2,
              'created_at' => now(),
              'updated_at' => now(),
              'image_src' => '酸化_方珪石.jpeg',
            ],
            [
              'title' => '赤銅鉱',
              'answers_id' => 9,
              'categories_id' => 2,
              'created_at' => now(),
              'updated_at' => now(),
              'image_src' => '酸化_赤銅鉱.png',
            ],
            [
              'title' => '赤鉄鉱',
              'answers_id' => 10,
              'categories_id' => 2,
              'created_at' => now(),
              'updated_at' => now(),
              'image_src' => '酸化_赤鉄鉱.png',
            ],
            [
              'title' => 'チタン鉄鉱',
              'answers_id' => 11,
              'categories_id' => 2,
              'created_at' => now(),
              'updated_at' => now(),
              'image_src' => '酸化_チタン鉄鉱.png',
            ],
            [
              'title' => 'ルチル(金紅石)',
              'answers_id' => 12,
              'categories_id' => 2,
              'created_at' => now(),
              'updated_at' => now(),
              'image_src' => '酸化_金紅石.png',
            ],
            [
              'title' => '鋭錐石',
              'answers_id' => 13,
              'categories_id' => 2,
              'created_at' => now(),
              'updated_at' => now(),
              'image_src' => '酸化_鋭錐石.png',
            ],
            [
              'title' => '軟マンガン鉱',
              'answers_id' => 14,
              'categories_id' => 2,
              'created_at' => now(),
              'updated_at' => now(),
              'image_src' => '酸化_軟マンガン鉱.png',
            ],
            [
              'title' => 'スズ石',
              'answers_id' => 15,
              'categories_id' => 2,
              'created_at' => now(),
              'updated_at' => now(),
              'image_src' => '酸化_スズ石.png',
            ],
            [
              'title' => '閃ウラン鉱',
              'answers_id' => 16,
              'categories_id' => 2,
              'created_at' => now(),
              'updated_at' => now(),
              'image_src' => '酸化_閃ウラン鉱.png',
            ],
            [
              'title' => '磁鉄鉱',
              'answers_id' => 17,
              'categories_id' => 2,
              'created_at' => now(),
              'updated_at' => now(),
              'image_src' => '酸化_磁鉄鉱.png',
            ],
            [
              'title' => 'クロム鉄鉱',
              'answers_id' => 18,
              'categories_id' => 2,
              'created_at' => now(),
              'updated_at' => now(),
              'image_src' => '酸化_クロム鉄鉱.png',
            ],
            [
              'title' => '針鉄鉱',
              'answers_id' => 19,
              'categories_id' => 2,
              'created_at' => now(),
              'updated_at' => now(),
              'image_src' => '酸化_針鉄鉱.png',
            ],
            [
              'title' => 'ギプス石',
              'answers_id' => 20,
              'categories_id' => 2,
              'created_at' => now(),
              'updated_at' => now(),
              'image_src' => '酸化_ギプス石.png',
            ],

            //③炭酸塩鉱物

            [
              'title' => '霰石',
              'answers_id' => 21,
              'categories_id' => 3,
              'created_at' => now(),
              'updated_at' => now(),
              'image_src' => '炭酸_霰石.png',
            ],
            [
              'title' => '方解石',
              'answers_id' => 22,
              'categories_id' => 3,
              'created_at' => now(),
              'updated_at' => now(),
              'image_src' => '炭酸_方解石.png',
            ],
            [
              'title' => '菱苦土石',
              'answers_id' => 23,
              'categories_id' => 3,
              'created_at' => now(),
              'updated_at' => now(),
              'image_src' => '炭酸_菱苦土石.png',
            ],
            [
              'title' => '菱マンガン鉱',
              'answers_id' => 24,
              'categories_id' => 3,
              'created_at' => now(),
              'updated_at' => now(),
              'image_src' => '炭酸_菱マンガン鉱.png',
            ],
            [
              'title' => '菱鉄鉱',
              'answers_id' => 25,
              'categories_id' => 3,
              'created_at' => now(),
              'updated_at' => now(),
              'image_src' => '炭酸_菱鉄鉱.png',
            ],
            [
              'title' => '菱亜鉛鉱',
              'answers_id' => 26,
              'categories_id' => 3,
              'created_at' => now(),
              'updated_at' => now(),
              'image_src' => '炭酸_菱亜鉛鉱.png',
            ],
            [
              'title' => '藍銅鉱',
              'answers_id' => 27,
              'categories_id' => 3,
              'created_at' => now(),
              'updated_at' => now(),
              'image_src' => '炭酸_藍銅鉱.png',
            ],
            [
              'title' => '孔雀石',
              'answers_id' => 28,
              'categories_id' => 3,
              'created_at' => now(),
              'updated_at' => now(),
              'image_src' => '炭酸_孔雀石.png',
            ],
            [
              'title' => '白鉛鉱',
              'answers_id' => 29,
              'categories_id' => 3,
              'created_at' => now(),
              'updated_at' => now(),
              'image_src' => '炭酸_白鉛鉱.png',
            ],
           
            //④珪酸塩鉱物
            [
              'title' => '緑簾石',
              'answers_id' => 30,
              'categories_id' => 4,
              'created_at' => now(),
              'updated_at' => now(),
              'image_src' => '珪酸_緑簾石.png',
            ],
            [
              'title' => '紅簾石',
              'answers_id' => 31,
              'categories_id' => 4,
              'created_at' => now(),
              'updated_at' => now(),
              'image_src' => '珪酸_紅簾石.png',
            ],
            [
              'title' => '藍晶石',
              'answers_id' => 32,
              'categories_id' => 4,
              'created_at' => now(),
              'updated_at' => now(),
              'image_src' => '珪酸_藍晶石.png',
            ],
            [
              'title' => '異極鉱',
              'answers_id' => 33,
              'categories_id' => 4,
              'created_at' => now(),
              'updated_at' => now(),
              'image_src' => '珪酸_異極鉱.png',
            ],
            [
              'title' => '十字石',
              'answers_id' => 34,
              'categories_id' => 4,
              'created_at' => now(),
              'updated_at' => now(),
              'image_src' => '珪酸_十字石.png',
            ],
            [
              'title' => '輝石グループ',
              'answers_id' => 35,
              'categories_id' => 4,
              'created_at' => now(),
              'updated_at' => now(),
              'image_src' => '珪酸_輝石.png',
            ],
            [
              'title' => 'バラ輝石',
              'answers_id' => 36,
              'categories_id' => 4,
              'created_at' => now(),
              'updated_at' => now(),
              'image_src' => '珪酸_バラ輝石.png',
            ],
            [
              'title' => 'ベスブ石',
              'answers_id' => 37,
              'categories_id' => 4,
              'created_at' => now(),
              'updated_at' => now(),
              'image_src' => '珪酸_ベスブ石.png',
            ],
            [
              'title' => '斧石',
              'answers_id' => 38,
              'categories_id' => 4,
              'created_at' => now(),
              'updated_at' => now(),
              'image_src' => '珪酸_斧石.png',
            ],
            [
              'title' => '珪灰石',
              'answers_id' => 39,
              'categories_id' => 4,
              'created_at' => now(),
              'updated_at' => now(),
              'image_src' => '珪酸_珪灰石.png',
            ],
            [
              'title' => '角閃石グループ',
              'answers_id' => 40,
              'categories_id' => 4,
              'created_at' => now(),
              'updated_at' => now(),
              'image_src' => '珪酸_角閃石.png',
            ],
            [
              'title' => '魚眼石',
              'answers_id' => 41,
              'categories_id' => 4,
              'created_at' => now(),
              'updated_at' => now(),
              'image_src' => '珪酸_魚眼石.png',
            ],
            [
              'title' => '長石グループ',
              'answers_id' => 42,
              'categories_id' => 4,
              'created_at' => now(),
              'updated_at' => now(),
              'image_src' => '珪酸_長石.png',
            ],
            [
              'title' => '霞石',
              'answers_id' => 43,
              'categories_id' => 4,
              'created_at' => now(),
              'updated_at' => now(),
              'image_src' => '珪酸_霞石.png',
            ],
            [
              'title' => '菫青石(きんせいせき)',
              'answers_id' => 44,
              'categories_id' => 4,
              'created_at' => now(),
              'updated_at' => now(),
              'image_src' => '珪酸_菫青石.png',
            ],
            [
              'title' => '滑石',
              'answers_id' => 45,
              'categories_id' => 4,
              'created_at' => now(),
              'updated_at' => now(),
              'image_src' => '珪酸_滑石.png',
            ],
            [
              'title' => 'カオリナイト',
              'answers_id' => 46,
              'categories_id' => 4,
              'created_at' => now(),
              'updated_at' => now(),
              'image_src' => '珪酸_カオリナイト.png',
            ],
            [
              'title' => '葉蝋石',
              'answers_id' => 47,
              'categories_id' => 4,
              'created_at' => now(),
              'updated_at' => now(),
              'image_src' => '珪酸_葉蝋石.png',
            ],
            [
              'title' => '葉長石',
              'answers_id' => 48,
              'categories_id' => 4,
              'created_at' => now(),
              'updated_at' => now(),
              'image_src' => '珪酸_葉長石.png',
            ],
            [
              'title' => '雲母グループ',
              'answers_id' => 49,
              'categories_id' => 4,
              'created_at' => now(),
              'updated_at' => now(),
              'image_src' => '珪酸_雲母.png',
            ],
            [
              'title' => '沸石グループ',
              'answers_id' => 50,
              'categories_id' => 4,
              'created_at' => now(),
              'updated_at' => now(),
              'image_src' => '珪酸_沸石.png',
            ],
            [
              'title' => '緑泥石',
              'answers_id' => 51,
              'categories_id' => 4,
              'created_at' => now(),
              'updated_at' => now(),
              'image_src' => '珪酸_緑泥石.png',
            ],
            [
              'title' => '珪孔雀石',
              'answers_id' => 52,
              'categories_id' => 4,
              'created_at' => now(),
              'updated_at' => now(),
              'image_src' => '珪酸_珪孔雀石.png',
            ],
            [
              'title' => '蛇紋石',
              'answers_id' => 53,
              'categories_id' => 4,
              'created_at' => now(),
              'updated_at' => now(),
              'image_src' => '珪酸_蛇紋石.png',
            ],

            //⑤硫化鉱物

            [
              'title' => '輝銀鉱',
              'answers_id' => 54,
              'categories_id' => 5,
              'created_at' => now(),
              'updated_at' => now(),
              'image_src' => '硫化_輝銀鉱.png',
            ],
            [
              'title' => '輝銅鉱',
              'answers_id' => 55,
              'categories_id' => 5,
              'created_at' => now(),
              'updated_at' => now(),
              'image_src' => '硫化_輝銅鉱.png',
            ],
            [
              'title' => '方鉛鉱',
              'answers_id' => 56,
              'categories_id' => 5,
              'created_at' => now(),
              'updated_at' => now(),
              'image_src' => '硫化_方鉛鉱.png',
            ],
            [
              'title' => '閃亜鉛鉱',
              'answers_id' => 57,
              'categories_id' => 5,
              'created_at' => now(),
              'updated_at' => now(),
              'image_src' => '硫化_閃亜鉛鉱.png',
            ],
            [
              'title' => '黄銅鉱',
              'answers_id' => 58,
              'categories_id' => 5,
              'created_at' => now(),
              'updated_at' => now(),
              'image_src' => '硫化_黄銅鉱.png',
            ],
            [
              'title' => '磁硫鉄鉱',
              'answers_id' => 59,
              'categories_id' => 5,
              'created_at' => now(),
              'updated_at' => now(),
              'image_src' => '硫化_磁硫鉄鉱.jpeg',
            ],
            [
              'title' => '銅藍',
              'answers_id' => 60,
              'categories_id' => 5,
              'created_at' => now(),
              'updated_at' => now(),
              'image_src' => '硫化_銅藍.png',
            ],
            [
              'title' => '辰砂',
              'answers_id' => 61,
              'categories_id' => 5,
              'created_at' => now(),
              'updated_at' => now(),
              'image_src' => '硫化_辰砂.png',
            ],
            [
              'title' => '鶏冠石',
              'answers_id' => 62,
              'categories_id' => 5,
              'created_at' => now(),
              'updated_at' => now(),
              'image_src' => '硫化_鶏冠石.png',
            ],
            [
              'title' => '輝安鉱',
              'answers_id' => 63,
              'categories_id' => 5,
              'created_at' => now(),
              'updated_at' => now(),
              'image_src' => '硫化_輝安鉱.png',
            ],
            [
              'title' => '輝蒼鉛鉱',
              'answers_id' => 64,
              'categories_id' => 5,
              'created_at' => now(),
              'updated_at' => now(),
              'image_src' => '硫化_輝蒼鉛鉱.png',
            ],
            [
              'title' => '黄鉄鉱',
              'answers_id' => 65,
              'categories_id' => 5,
              'created_at' => now(),
              'updated_at' => now(),
              'image_src' => '硫化_黄鉄鉱.png',
            ],
            [
              'title' => '輝コバルト鉱',
              'answers_id' => 66,
              'categories_id' => 5,
              'created_at' => now(),
              'updated_at' => now(),
              'image_src' => '硫化_輝コバルト鉱.png',
            ],
            [
              'title' => '輝水鉛鉱',
              'answers_id' => 67,
              'categories_id' => 5,
              'created_at' => now(),
              'updated_at' => now(),
              'image_src' => '硫化_輝水鉛鉱.png',
            ],

            //⑥宝石
            [
              'title' => 'ダイアモンド',
              'answers_id' => 68,
              'categories_id' => 6,
              'created_at' => now(),
              'updated_at' => now(),
              'image_src' => '宝石_ダイアモンド.png',
            ],
            [
              'title' => 'ルビー',
              'answers_id' => 69,
              'categories_id' => 6,
              'created_at' => now(),
              'updated_at' => now(),
              'image_src' => '宝石_ルビー.png',
            ],
            [
              'title' => 'サファイア',
              'answers_id' => 70,
              'categories_id' => 6,
              'created_at' => now(),
              'updated_at' => now(),
              'image_src' => '宝石_サファイア.png',
            ],
            [
              'title' => 'エメラルド',
              'answers_id' => 71,
              'categories_id' => 6,
              'created_at' => now(),
              'updated_at' => now(),
              'image_src' => '宝石_エメラルド.png',
            ],
            [
              'title' => 'アクアマリン',
              'answers_id' => 72,
              'categories_id' => 6,
              'created_at' => now(),
              'updated_at' => now(),
              'image_src' => '宝石_アクアマリン.png',
            ],
            [
              'title' => 'トパーズ',
              'answers_id' => 73,
              'categories_id' => 6,
              'created_at' => now(),
              'updated_at' => now(),
              'image_src' => '宝石_トパーズ.png',
            ],
            [
              'title' => 'スピネル',
              'answers_id' => 74,
              'categories_id' => 6,
              'created_at' => now(),
              'updated_at' => now(),
              'image_src' => '宝石_スピネル.png',
            ],
            [
              'title' => 'ジルコン',
              'answers_id' => 75,
              'categories_id' => 6,
              'created_at' => now(),
              'updated_at' => now(),
              'image_src' => '宝石_ジルコン.png',
            ],
            [
              'title' => 'トルマリン',
              'answers_id' => 76,
              'categories_id' => 6,
              'created_at' => now(),
              'updated_at' => now(),
              'image_src' => '宝石_トルマリン.png',
            ],
            [
              'title' => 'ガーネット',
              'answers_id' => 77,
              'categories_id' => 6,
              'created_at' => now(),
              'updated_at' => now(),
              'image_src' => '宝石_ガーネット.png',
            ],
            [
              'title' => 'ジェード',
              'answers_id' => 78,
              'categories_id' => 6,
              'created_at' => now(),
              'updated_at' => now(),
              'image_src' => '宝石_ジェード.png',
            ],
            [
              'title' => 'オパール',
              'answers_id' => 79,
              'categories_id' => 6,
              'created_at' => now(),
              'updated_at' => now(),
              'image_src' => '宝石_オパール.png',
            ],
            [
              'title' => 'ペリドット',
              'answers_id' => 80,
              'categories_id' => 6,
              'created_at' => now(),
              'updated_at' => now(),
              'image_src' => '宝石_ペリドット.png',
            ],
            [
              'title' => 'アメジスト',
              'answers_id' => 81,
              'categories_id' => 6,
              'created_at' => now(),
              'updated_at' => now(),
              'image_src' => '宝石_アメジスト.png',
            ],
            [
              'title' => 'アゲート',
              'answers_id' => 82,
              'categories_id' => 6,
              'created_at' => now(),
              'updated_at' => now(),
              'image_src' => '宝石_アゲート.png',
            ],
            [
              'title' => 'クリソベリル',
              'answers_id' => 83,
              'categories_id' => 6,
              'created_at' => now(),
              'updated_at' => now(),
              'image_src' => '宝石_クリソベリル.png',
            ],
            [
              'title' => 'ムーンストーン',
              'answers_id' => 84,
              'categories_id' => 6,
              'created_at' => now(),
              'updated_at' => now(),
              'image_src' => '宝石_ムーンストーン.png',
            ],
            [
              'title' => 'ターコイズ',
              'answers_id' => 85,
              'categories_id' => 6,
              'created_at' => now(),
              'updated_at' => now(),
              'image_src' => '宝石_ターコイズ.png',
            ],
            [
              'title' => 'ラピスラズリ',
              'answers_id' => 86,
              'categories_id' => 6,
              'created_at' => now(),
              'updated_at' => now(),
              'image_src' => '宝石_ラピスラズリ.png',
            ],
            [
              'title' => 'アンバー',
              'answers_id' => 87,
              'categories_id' => 6,
              'created_at' => now(),
              'updated_at' => now(),
              'image_src' => '宝石_アンバー.png',
            ],

            //⑦その他
            [
              'title' => '燐灰石',
              'answers_id' => 88,
              'categories_id' => 7,
              'created_at' => now(),
              'updated_at' => now(),
              'image_src' => 'その他_燐灰石.png',
            ],
            [
              'title' => '燐灰ウラン鉱',
              'answers_id' => 89,
              'categories_id' => 7,
              'created_at' => now(),
              'updated_at' => now(),
              'image_src' => 'その他_燐灰ウラン鉱.png',
            ],
            [
              'title' => 'スコロド石',
              'answers_id' => 90,
              'categories_id' => 7,
              'created_at' => now(),
              'updated_at' => now(),
              'image_src' => 'その他_スコロド石.png',
            ],
            [
              'title' => '藍鉄鋼',
              'answers_id' => 91,
              'categories_id' => 7,
              'created_at' => now(),
              'updated_at' => now(),
              'image_src' => 'その他_藍鉄鋼.png',
            ],
            [
              'title' => 'アダム鉱',
              'answers_id' => 92,
              'categories_id' => 7,
              'created_at' => now(),
              'updated_at' => now(),
              'image_src' => 'その他_アダム鉱.png',
            ],
            [
              'title' => '灰重石',
              'answers_id' => 93,
              'categories_id' => 7,
              'created_at' => now(),
              'updated_at' => now(),
              'image_src' => 'その他_灰重石.png',
            ],
            [
              'title' => '蛍石',
              'answers_id' => 94,
              'categories_id' => 7,
              'created_at' => now(),
              'updated_at' => now(),
              'image_src' => 'その他_蛍石.png',
            ],
            [
              'title' => '岩塩',
              'answers_id' => 95,
              'categories_id' => 7,
              'created_at' => now(),
              'updated_at' => now(),
              'image_src' => 'その他_岩塩.png',
            ],
            [
              'title' => '氷晶石',
              'answers_id' => 96,
              'categories_id' => 7,
              'created_at' => now(),
              'updated_at' => now(),
              'image_src' => 'その他_氷晶石.png',
            ],
            [
              'title' => '石膏',
              'answers_id' => 97,
              'categories_id' => 7,
              'created_at' => now(),
              'updated_at' => now(),
              'image_src' => 'その他_石膏.png',
            ],
            [
              'title' => '重晶石',
              'answers_id' => 98,
              'categories_id' => 7,
              'created_at' => now(),
              'updated_at' => now(),
              'image_src' => 'その他_重晶石.png',
            ],
            [
              'title' => '胆礬(たんばん)',
              'answers_id' => 99,
              'categories_id' => 7,
              'created_at' => now(),
              'updated_at' => now(),
              'image_src' => 'その他_胆礬.png',
            ],
            [
              'title' => '明礬石',
              'answers_id' => 100,
              'categories_id' => 7,
              'created_at' => now(),
              'updated_at' => now(),
              'image_src' => 'その他_明礬石.jpeg',
            ]
          ]
        );
      }
    }