<?php

use Illuminate\Database\Seeder;

class QuizTableSeeder extends Seeder
{
    /**
     * Run the database seeds.
     *
     * @return void
     */
    public function run()
    {
        DB::table('quizzes')->truncate();

        DB::table('quizzes')->insert(
          [
            //①元素鉱物
            [
              'title' => '硫黄',
              'answers_id' => 1,
              'categories_id' => 1,
              'created_at' => now(),
              'updated_at' => now(),
              'image_src' => '硫黄.png',
            ],
            [
              'title' => '自然金',
              'answers_id' => 2,
              'categories_id' => 1,
              'created_at' => now(),
              'updated_at' => now(),
              'image_src' => '自然金.png',
            ],
            [
              'title' => '自然銀',
              'answers_id' => 3,
              'categories_id' => 1,
              'created_at' => now(),
              'updated_at' => now(),
              'image_src' => '自然銀.png',
            ],
            [
              'title' => '自然銅',
              'answers_id' => 4,
              'categories_id' => 1,
              'created_at' => now(),
              'updated_at' => now(),
              'image_src' => '自然銅.png',
            ],
            [
              'title' => '白金',
              'answers_id' => 5,
              'categories_id' => 1,
              'created_at' => now(),
              'updated_at' => now(),
              'image_src' => '白金.png',
            ],
            //②酸化鉱物

            [
              'title' => 'クォーツ(石英)',
              'answers_id' => 6,
              'categories_id' => 2,
              'created_at' => now(),
              'updated_at' => now(),
              'image_src' => '石英.png',
            ],
            [
              'title' => '鱗珪石',
              'answers_id' => 7,
              'categories_id' => 2,
              'created_at' => now(),
              'updated_at' => now(),
              'image_src' => '鱗珪石.png',
            ],
            [
              'title' => '方珪石',
              'answers_id' => 8,
              'categories_id' => 2,
              'created_at' => now(),
              'updated_at' => now(),
              'image_src' => '方珪石.png',
            ],
            [
              'title' => '赤銅鉱',
              'answers_id' => 9,
              'categories_id' => 2,
              'created_at' => now(),
              'updated_at' => now(),
              'image_src' => '赤銅鉱.png',
            ],
            [
              'title' => '赤鉄鉱',
              'answers_id' => 10,
              'categories_id' => 2,
              'created_at' => now(),
              'updated_at' => now(),
              'image_src' => '赤鉄鉱.png',
            ],
            [
              'title' => 'チタン鉄鉱',
              'answers_id' => 11,
              'categories_id' => 2,
              'created_at' => now(),
              'updated_at' => now(),
              'image_src' => 'チタン鉄鉱.png',
            ],
            [
              'title' => 'ルチル(金紅石)',
              'answers_id' => 12,
              'categories_id' => 2,
              'created_at' => now(),
              'updated_at' => now(),
              'image_src' => '金紅石.png',
            ],
            [
              'title' => '鋭錐石',
              'answers_id' => 13,
              'categories_id' => 2,
              'created_at' => now(),
              'updated_at' => now(),
              'image_src' => '鋭錐石.png',
            ],
            [
              'title' => '軟マンガン鉱',
              'answers_id' => 14,
              'categories_id' => 2,
              'created_at' => now(),
              'updated_at' => now(),
              'image_src' => '軟マンガン鉱.png',
            ],
            [
              'title' => 'スズ石',
              'answers_id' => 15,
              'categories_id' => 2,
              'created_at' => now(),
              'updated_at' => now(),
              'image_src' => 'スズ石.png',
            ],
            [
              'title' => '閃ウラン鉱',
              'answers_id' => 16,
              'categories_id' => 2,
              'created_at' => now(),
              'updated_at' => now(),
              'image_src' => '閃ウラン鉱.png',
            ],
            [
              'title' => '磁鉄鉱',
              'answers_id' => 17,
              'categories_id' => 2,
              'created_at' => now(),
              'updated_at' => now(),
              'image_src' => '磁鉄鉱.png',
            ],
            [
              'title' => 'クロム鉄鉱',
              'answers_id' => 18,
              'categories_id' => 2,
              'created_at' => now(),
              'updated_at' => now(),
              'image_src' => 'クロム鉄鉱.png',
            ],
            [
              'title' => '針鉄鉱',
              'answers_id' => 19,
              'categories_id' => 2,
              'created_at' => now(),
              'updated_at' => now(),
              'image_src' => '針鉄鉱.png',
            ],
            [
              'title' => 'ギプス石',
              'answers_id' => 20,
              'categories_id' => 2,
              'created_at' => now(),
              'updated_at' => now(),
              'image_src' => 'ギプス石.png',
            ],

            //③炭酸塩鉱物

            [
              'title' => '霰石',
              'answers_id' => 21,
              'categories_id' => 3,
              'created_at' => now(),
              'updated_at' => now(),
              'image_src' => '霰石.png',
            ],
            [
              'title' => '方解石',
              'answers_id' => 22,
              'categories_id' => 3,
              'created_at' => now(),
              'updated_at' => now(),
              'image_src' => '方解石.png',
            ],
            [
              'title' => '菱苦土石',
              'answers_id' => 23,
              'categories_id' => 3,
              'created_at' => now(),
              'updated_at' => now(),
              'image_src' => '菱苦土石.png',
            ],
            [
              'title' => '菱マンガン鉱',
              'answers_id' => 24,
              'categories_id' => 3,
              'created_at' => now(),
              'updated_at' => now(),
              'image_src' => '菱マンガン鉱.png',
            ],
            [
              'title' => '菱鉄鉱',
              'answers_id' => 25,
              'categories_id' => 3,
              'created_at' => now(),
              'updated_at' => now(),
              'image_src' => '菱鉄鉱.png',
            ],
            [
              'title' => '菱亜鉛鉱',
              'answers_id' => 26,
              'categories_id' => 3,
              'created_at' => now(),
              'updated_at' => now(),
              'image_src' => '菱亜鉛鉱.png',
            ],
            [
              'title' => '藍銅鉱',
              'answers_id' => 27,
              'categories_id' => 3,
              'created_at' => now(),
              'updated_at' => now(),
              'image_src' => '藍銅鉱.png',
            ],
            [
              'title' => '孔雀石',
              'answers_id' => 28,
              'categories_id' => 3,
              'created_at' => now(),
              'updated_at' => now(),
              'image_src' => '孔雀石.png',
            ],
            [
              'title' => '白鉛鉱',
              'answers_id' => 29,
              'categories_id' => 3,
              'created_at' => now(),
              'updated_at' => now(),
              'image_src' => '白鉛鉱.png',
            ],
           
            //④珪酸塩鉱物
            [
              'title' => '緑簾石',
              'answers_id' => 30,
              'categories_id' => 4,
              'created_at' => now(),
              'updated_at' => now(),
              'image_src' => '緑簾石.png',
            ],
            [
              'title' => '紅簾石',
              'answers_id' => 31,
              'categories_id' => 4,
              'created_at' => now(),
              'updated_at' => now(),
              'image_src' => '紅簾石.png',
            ],
            [
              'title' => '藍晶石',
              'answers_id' => 32,
              'categories_id' => 4,
              'created_at' => now(),
              'updated_at' => now(),
              'image_src' => '藍晶石.png',
            ],
            [
              'title' => '異極鉱',
              'answers_id' => 33,
              'categories_id' => 4,
              'created_at' => now(),
              'updated_at' => now(),
              'image_src' => '異極鉱.png',
            ],
            [
              'title' => '十字石',
              'answers_id' => 34,
              'categories_id' => 4,
              'created_at' => now(),
              'updated_at' => now(),
              'image_src' => '十字石.png',
            ],
            [
              'title' => '輝石グループ',
              'answers_id' => 35,
              'categories_id' => 4,
              'created_at' => now(),
              'updated_at' => now(),
              'image_src' => '輝石.png',
            ],
            [
              'title' => 'バラ輝石',
              'answers_id' => 36,
              'categories_id' => 4,
              'created_at' => now(),
              'updated_at' => now(),
              'image_src' => 'バラ輝石.png',
            ],
            [
              'title' => 'ベスブ石',
              'answers_id' => 37,
              'categories_id' => 4,
              'created_at' => now(),
              'updated_at' => now(),
              'image_src' => 'ベスブ石.png',
            ],
            [
              'title' => '斧石',
              'answers_id' => 38,
              'categories_id' => 4,
              'created_at' => now(),
              'updated_at' => now(),
              'image_src' => '斧石.png',
            ],
            [
              'title' => '珪灰石',
              'answers_id' => 39,
              'categories_id' => 4,
              'created_at' => now(),
              'updated_at' => now(),
              'image_src' => '珪灰石.png',
            ],
            [
              'title' => '角閃石グループ',
              'answers_id' => 40,
              'categories_id' => 4,
              'created_at' => now(),
              'updated_at' => now(),
              'image_src' => '角閃石.png',
            ],
            [
              'title' => '魚眼石',
              'answers_id' => 41,
              'categories_id' => 4,
              'created_at' => now(),
              'updated_at' => now(),
              'image_src' => '魚眼石.png',
            ],
            [
              'title' => '長石グループ',
              'answers_id' => 42,
              'categories_id' => 4,
              'created_at' => now(),
              'updated_at' => now(),
              'image_src' => '長石.png',
            ],
            [
              'title' => '霞石',
              'answers_id' => 43,
              'categories_id' => 4,
              'created_at' => now(),
              'updated_at' => now(),
              'image_src' => '霞石.png',
            ],
            [
              'title' => '菫青石(きんせいせき)',
              'answers_id' => 44,
              'categories_id' => 4,
              'created_at' => now(),
              'updated_at' => now(),
              'image_src' => '菫青石.png',
            ],
            [
              'title' => '滑石',
              'answers_id' => 45,
              'categories_id' => 4,
              'created_at' => now(),
              'updated_at' => now(),
              'image_src' => '滑石.png',
            ],
            [
              'title' => 'カオリナイト',
              'answers_id' => 46,
              'categories_id' => 4,
              'created_at' => now(),
              'updated_at' => now(),
              'image_src' => 'カオリナイト.png',
            ],
            [
              'title' => '葉蝋石',
              'answers_id' => 47,
              'categories_id' => 4,
              'created_at' => now(),
              'updated_at' => now(),
              'image_src' => '葉蝋石.png',
            ],
            [
              'title' => '葉長石',
              'answers_id' => 48,
              'categories_id' => 4,
              'created_at' => now(),
              'updated_at' => now(),
              'image_src' => '葉長石.png',
            ],
            [
              'title' => '雲母グループ',
              'answers_id' => 49,
              'categories_id' => 4,
              'created_at' => now(),
              'updated_at' => now(),
              'image_src' => '雲母.png',
            ],
            [
              'title' => '沸石グループ',
              'answers_id' => 50,
              'categories_id' => 4,
              'created_at' => now(),
              'updated_at' => now(),
              'image_src' => '沸石.png',
            ],
            [
              'title' => '緑泥石',
              'answers_id' => 51,
              'categories_id' => 4,
              'created_at' => now(),
              'updated_at' => now(),
              'image_src' => '緑泥石.png',
            ],
            [
              'title' => '珪孔雀石',
              'answers_id' => 52,
              'categories_id' => 4,
              'created_at' => now(),
              'updated_at' => now(),
              'image_src' => '珪孔雀石.png',
            ],
            [
              'title' => '蛇紋石',
              'answers_id' => 53,
              'categories_id' => 4,
              'created_at' => now(),
              'updated_at' => now(),
              'image_src' => '蛇紋石.png',
            ],

            //⑤硫化鉱物

            [
              'title' => '輝銀鉱',
              'answers_id' => 54,
              'categories_id' => 5,
              'created_at' => now(),
              'updated_at' => now(),
              'image_src' => '輝銀鉱.png',
            ],
            [
              'title' => '輝銅鉱',
              'answers_id' => 55,
              'categories_id' => 5,
              'created_at' => now(),
              'updated_at' => now(),
              'image_src' => '輝銅鉱.png',
            ],
            [
              'title' => '方鉛鉱',
              'answers_id' => 56,
              'categories_id' => 5,
              'created_at' => now(),
              'updated_at' => now(),
              'image_src' => '方鉛鉱.png',
            ],
            [
              'title' => '閃亜鉛鉱',
              'answers_id' => 57,
              'categories_id' => 5,
              'created_at' => now(),
              'updated_at' => now(),
              'image_src' => '閃亜鉛鉱.png',
            ],
            [
              'title' => '黄銅鉱',
              'answers_id' => 58,
              'categories_id' => 5,
              'created_at' => now(),
              'updated_at' => now(),
              'image_src' => '黄銅鉱.png',
            ],
            [
              'title' => '磁硫鉄鉱',
              'answers_id' => 59,
              'categories_id' => 5,
              'created_at' => now(),
              'updated_at' => now(),
              'image_src' => '磁硫鉄鉱.png',
            ],
            [
              'title' => '銅藍',
              'answers_id' => 60,
              'categories_id' => 5,
              'created_at' => now(),
              'updated_at' => now(),
              'image_src' => '銅藍.png',
            ],
            [
              'title' => '辰砂',
              'answers_id' => 61,
              'categories_id' => 5,
              'created_at' => now(),
              'updated_at' => now(),
              'image_src' => '辰砂.png',
            ],
            [
              'title' => '鶏冠石',
              'answers_id' => 62,
              'categories_id' => 5,
              'created_at' => now(),
              'updated_at' => now(),
              'image_src' => '鶏冠石.png',
            ],
            [
              'title' => '輝安鉱',
              'answers_id' => 63,
              'categories_id' => 5,
              'created_at' => now(),
              'updated_at' => now(),
              'image_src' => '輝安鉱.png',
            ],
            [
              'title' => '輝蒼鉛鉱',
              'answers_id' => 64,
              'categories_id' => 5,
              'created_at' => now(),
              'updated_at' => now(),
              'image_src' => '輝蒼鉛鉱.png',
            ],
            [
              'title' => '黄鉄鉱',
              'answers_id' => 65,
              'categories_id' => 5,
              'created_at' => now(),
              'updated_at' => now(),
              'image_src' => '黄鉄鉱.png',
            ],
            [
              'title' => '輝コバルト鉱',
              'answers_id' => 66,
              'categories_id' => 5,
              'created_at' => now(),
              'updated_at' => now(),
              'image_src' => '輝コバルト鉱.png',
            ],
            [
              'title' => '輝水鉛鉱',
              'answers_id' => 67,
              'categories_id' => 5,
              'created_at' => now(),
              'updated_at' => now(),
              'image_src' => '輝水鉛鉱.png',
            ],

            //⑥宝石
            [
              'title' => 'ダイアモンド',
              'answers_id' => 68,
              'categories_id' => 6,
              'created_at' => now(),
              'updated_at' => now(),
              'image_src' => 'ダイアモンド.png',
            ],
            [
              'title' => 'ルビー',
              'answers_id' => 69,
              'categories_id' => 6,
              'created_at' => now(),
              'updated_at' => now(),
              'image_src' => 'ルビー.png',
            ],
            [
              'title' => 'サファイア',
              'answers_id' => 70,
              'categories_id' => 6,
              'created_at' => now(),
              'updated_at' => now(),
              'image_src' => 'サファイア.png',
            ],
            [
              'title' => 'エメラルド',
              'answers_id' => 71,
              'categories_id' => 6,
              'created_at' => now(),
              'updated_at' => now(),
              'image_src' => 'エメラルド.png',
            ],
            [
              'title' => 'アクアマリン',
              'answers_id' => 72,
              'categories_id' => 6,
              'created_at' => now(),
              'updated_at' => now(),
              'image_src' => 'アクアマリン.png',
            ],
            [
              'title' => 'トパーズ',
              'answers_id' => 73,
              'categories_id' => 6,
              'created_at' => now(),
              'updated_at' => now(),
              'image_src' => 'トパーズ.png',
            ],
            [
              'title' => 'スピネル',
              'answers_id' => 74,
              'categories_id' => 6,
              'created_at' => now(),
              'updated_at' => now(),
              'image_src' => 'スピネル.png',
            ],
            [
              'title' => 'ジルコン',
              'answers_id' => 75,
              'categories_id' => 6,
              'created_at' => now(),
              'updated_at' => now(),
              'image_src' => 'ジルコン.png',
            ],
            [
              'title' => 'トルマリン',
              'answers_id' => 76,
              'categories_id' => 6,
              'created_at' => now(),
              'updated_at' => now(),
              'image_src' => 'トルマリン.png',
            ],
            [
              'title' => 'ガーネット',
              'answers_id' => 77,
              'categories_id' => 6,
              'created_at' => now(),
              'updated_at' => now(),
              'image_src' => 'ガーネット.png',
            ],
            [
              'title' => 'ジェード',
              'answers_id' => 78,
              'categories_id' => 6,
              'created_at' => now(),
              'updated_at' => now(),
              'image_src' => 'ジェード.png',
            ],
            [
              'title' => 'オパール',
              'answers_id' => 79,
              'categories_id' => 6,
              'created_at' => now(),
              'updated_at' => now(),
              'image_src' => 'オパール.png',
            ],
            [
              'title' => 'ペリドット',
              'answers_id' => 80,
              'categories_id' => 6,
              'created_at' => now(),
              'updated_at' => now(),
              'image_src' => 'ペリドット.png',
            ],
            [
              'title' => 'アメジスト',
              'answers_id' => 81,
              'categories_id' => 6,
              'created_at' => now(),
              'updated_at' => now(),
              'image_src' => 'アメジスト.png',
            ],
            [
              'title' => 'アゲート',
              'answers_id' => 82,
              'categories_id' => 6,
              'created_at' => now(),
              'updated_at' => now(),
              'image_src' => 'アゲート.png',
            ],
            [
              'title' => 'クリソベリル',
              'answers_id' => 83,
              'categories_id' => 6,
              'created_at' => now(),
              'updated_at' => now(),
              'image_src' => 'クリソベリル.png',
            ],
            [
              'title' => 'ムーンストーン',
              'answers_id' => 84,
              'categories_id' => 6,
              'created_at' => now(),
              'updated_at' => now(),
              'image_src' => 'ムーンストーン.png',
            ],
            [
              'title' => 'ターコイズ',
              'answers_id' => 85,
              'categories_id' => 6,
              'created_at' => now(),
              'updated_at' => now(),
              'image_src' => 'ターコイズ.png',
            ],
            [
              'title' => 'ラピスラズリ',
              'answers_id' => 86,
              'categories_id' => 6,
              'created_at' => now(),
              'updated_at' => now(),
              'image_src' => 'ラピスラズリ.png',
            ],
            [
              'title' => 'アンバー',
              'answers_id' => 87,
              'categories_id' => 6,
              'created_at' => now(),
              'updated_at' => now(),
              'image_src' => 'アンバー.png',
            ],

            //⑦その他
            [
              'title' => '燐灰石',
              'answers_id' => 88,
              'categories_id' => 7,
              'created_at' => now(),
              'updated_at' => now(),
              'image_src' => '燐灰石.png',
            ],
            [
              'title' => '燐灰ウラン鉱',
              'answers_id' => 89,
              'categories_id' => 7,
              'created_at' => now(),
              'updated_at' => now(),
              'image_src' => '燐灰ウラン鉱.png',
            ],
            [
              'title' => 'スコロド石',
              'answers_id' => 90,
              'categories_id' => 7,
              'created_at' => now(),
              'updated_at' => now(),
              'image_src' => '.png',
            ],
            [
              'title' => '藍鉄鋼',
              'answers_id' => 91,
              'categories_id' => 7,
              'created_at' => now(),
              'updated_at' => now(),
              'image_src' => '藍鉄鋼.png',
            ],
            [
              'title' => 'アダム鉱',
              'answers_id' => 92,
              'categories_id' => 7,
              'created_at' => now(),
              'updated_at' => now(),
              'image_src' => 'アダム鉱.png',
            ],
            [
              'title' => '灰重石',
              'answers_id' => 93,
              'categories_id' => 7,
              'created_at' => now(),
              'updated_at' => now(),
              'image_src' => '灰重石.png',
            ],
            [
              'title' => '蛍石',
              'answers_id' => 94,
              'categories_id' => 7,
              'created_at' => now(),
              'updated_at' => now(),
              'image_src' => '蛍石.png',
            ],
            [
              'title' => '岩塩',
              'answers_id' => 95,
              'categories_id' => 7,
              'created_at' => now(),
              'updated_at' => now(),
              'image_src' => '岩塩.png',
            ],
            [
              'title' => '氷晶石',
              'answers_id' => 96,
              'categories_id' => 7,
              'created_at' => now(),
              'updated_at' => now(),
              'image_src' => '氷晶石.png',
            ],
            [
              'title' => '石膏',
              'answers_id' => 97,
              'categories_id' => 7,
              'created_at' => now(),
              'updated_at' => now(),
              'image_src' => '石膏.png',
            ],
            [
              'title' => '重晶石',
              'answers_id' => 98,
              'categories_id' => 7,
              'created_at' => now(),
              'updated_at' => now(),
              'image_src' => '重晶石.png',
            ],
            [
              'title' => '胆礬(たんばん)',
              'answers_id' => 99,
              'categories_id' => 7,
              'created_at' => now(),
              'updated_at' => now(),
              'image_src' => '胆礬.png',
            ],
            [
              'title' => '明礬石',
              'answers_id' => 100,
              'categories_id' => 7,
              'created_at' => now(),
              'updated_at' => now(),
              'image_src' => '.png',
            ]
          ]
        );
      }
    }